# Generated by Django 4.1 on 2022-08-10 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionCategorias', '0001_CreacionTablaCategorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='adminId',
            field=models.ForeignKey(db_column='admin_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
